### PR TITLE
Feature/signature

### PR DESCRIPTION
**Pull request by apmccartney**
+ Updated metaconfigure
+ Added signature update script
+ Configured travis to run script on successful builds

### CODE REVIEW

**Comment by jlconlin** [comment]
So the testing needs to be updated on this. It's really bad—relative to our standard. If we are going to require 90% coverage, we better not make exceptions for ourselves.

**Comment by jlconlin** [comment]
I don't like how all the docs from metaconfigure got pulled into this, but I guess there's no way around that.

**Comment by jlconlin** [comment]
While you're at it, let's add gcc on Mac to the testing.

**Comment by apmccartney** [comment]
> So the testing needs to be updated on this. It's really bad—relative to our standard. If we are going to require 90% coverage, we better not make exceptions for ourselves.

We've spoken about this before. The basis of dimwits is a collection of metaprograms. In C++, metaprograms

+ operate on types rather than values and 
+ are called at compile-time rather than at runtime. 

Consequently the sorts of testing statistics we collect just aren't meaningful for these portions of the library. `gcov` coverage metrics collect information from test execution, i.e. at runtime. Evaluating metaprogram test coverage with runtime statistics is like trying to taste music.

In [hana](https://github.com/boostorg/hana)-style metaprogramming in particular, metaprograms are written in terms of functions (so `gcov` thinks they're testable), but as metaprograms, unlike a traditional function, their correctness isn't defined by the value they return but rather **the type of value** they return. 

Here's a good [example](https://coveralls.io/builds/12503171/source?filename=src%2Fdimwits%2Funit%2Fsrc%2Fdimensionality.hpp). The `deduceDimensionality` metafunction computes a type. Each instantiation of the `dimensionality` function template calls to the `deduceDimensionality` metafunction. Consider the the [dimensionality test](https://github.com/njoy/DimensionalAnalysis/blob/master/src/dimwits/unit/test/dimensionality.test.cpp). Each call to the `dimensionality` function is exercising the `deduceDimensionality` metafunction, but because the work is done at compile time, `gcov` **can't** detect that.

**Comment by apmccartney** [comment]
> While you're at it, let's add gcc on Mac to the testing.

Outside the scope of this work, but worth filing an issue for

**Review by jlconlin — APPROVED** [review]

**Comment by jlconlin** [comment]
I have a vague memory about testing this project. Sorry to have forgotten.

I couldn't sleep so I added Mac testing to this project. It was a simple 3-line change in the travis script.

**Pull request merged**
